import styles from "./texts-styles.module.css";

const getTxtFromJsx = (jsx: JSX.Element): string => {
    // recursively extract text from JSX
    if (typeof jsx === "string") {
        return jsx;
    }
    if (Array.isArray(jsx)) {
        return jsx.map(getTxtFromJsx).join(" ");
    }
    if (typeof jsx === "object") {
        return getTxtFromJsx(jsx.props.children);
    }
    return "";
}

class ProjectsText {

    /* Expanded descriptions */
    public static worldAtlasExpanded = <>
        <p className={styles.paragraph}>WorldAtlas is a 3D globe visualization built with Three.js, offering an interactive interface for an intuitive user experience.</p>
        <p className={styles.paragraph}>Users can navigate the globe in 3D, zoom, rotate, and select countries to access detailed information. The app is fully responsive, working seamlessly across all devices, including mobile phones and tablets.</p>
    </>;

    public static restaurantExpanded = <>
        <p className={styles.paragraph}>RestaurantBooking is a table reservation system designed to simplify bookings for both customers and staff through user-friendly web and mobile apps for iOS and Android.</p>
        <p className={styles.paragraph}>Customers can reserve tables, browse menus, and place orders, while staff can efficiently manage reservations and orders in real time. The system is secure, scalable, and supports multiple restaurants and users.</p>
    </>;

    public static checkersExpanded = <>
        <p className={styles.paragraph}>!Checkers (Bang Checkers) is a multiplayer game developed in just six days by a small team, demonstrating effective project collaboration.</p>
        <p className={styles.paragraph}>Players can compete in real time, chat, and review their game history. The game is designed to be secure and scalable, supporting multiple simultaneous matches.</p>
    </>;

    public static reinforcementLearningExpanded = <>
        <p className={styles.paragraph}>GridWorld is a 2D simulation game that allows players to experiment with reinforcement learning algorithms such as Value Iteration, Q-Learning, and Monte-Carlo.</p>
        <p className={styles.paragraph}>Users can train agents to complete tasks, analyze their performance, and compare algorithms. The game offers an engaging way to learn reinforcement learning concepts.</p>
    </>;

    public static xcoversExpanded = <>
        <p className={styles.paragraph}>A website created for a family business during my time as a Psychology graduate, blending professional and amateur design elements.</p>
    </>;

    public static onlineExperiment1Expanded = <>
        <p className={styles.paragraph}>An experiment focused on hypothesis updating, conducted as part of a broader research project to enhance understanding of cognitive processes.</p>
    </>;

    public static blackJackExpanded = <>
        <p className={styles.paragraph}>BlackJack is an online card game featuring smooth animations powered by WebGL and canvas, with a robust back-end incorporating unit tests, web sockets, and Spring Security.</p>
        <p className={styles.paragraph}>Players can engage in real-time matches, chat, and track their game history. The game is built for scalability and security, supporting multiple concurrent players.</p>
    </>;

    public static smartPotExpanded = <>
        <p className={styles.paragraph}>Smart Pot is an ESP32-based self-watering planter that reads a capacitive soil moisture probe on GPIO34 and controls a 12V peristaltic pump through a Gravity MOSFET module on GPIO26. The physical build combines a 12V supply, 5V buck converter, common-ground wiring, flyback protection, status LEDs, tubing, and a 3D printed enclosure/reservoir assembly.</p>
        <p className={styles.paragraph}>The firmware is written in Arduino C++ with PlatformIO. It stores dry and wet calibration points in ESP32 Preferences, converts raw ADC readings into a calibrated moisture percentage, and clamps every manual or automatic pump pulse to conservative bounds. Automatic watering is deliberately disabled on every boot, requires valid calibration before it can be enabled, observes a cooldown after watering, and is locked out during OTA updates.</p>
        <p className={styles.paragraph}>The network layer supports protected Wi-Fi provisioning through a setup access point, then exposes a Basic Auth LAN dashboard at smart-pot.local using mDNS. The dashboard is generated by the firmware itself and provides status, moisture readings, calibration actions, settings for threshold/pulse/cooldown/sample interval, manual watering, OTA availability, and recent watering history.</p>
        <p className={styles.paragraph}>There is also a serial console for bench testing and recovery commands: read moisture, print combined plant/network status, run a manual pump pulse, perform a GPIO diagnostic sweep, capture calibration points, tune runtime settings, and clear Wi-Fi credentials to reopen setup mode.</p>
        <p className={styles.paragraph}>The repo is set up beyond a one-off prototype. It includes PlatformIO native GoogleTest coverage with fake Arduino, Wi-Fi, Preferences, OTA, and WebServer layers; Playwright tests for the embedded dashboard through a local harness; and hardware smoke scripts for status schema, authentication, and manual watering checks.</p>
    </>;

    public static networkGraphExpanded = <>
        <p className={styles.paragraph}>NetworkGraph is an interactive visualization of Facebook connections, built using Three.js and 3d-force-graph.</p>
        <p className={styles.paragraph}>A custom web crawler gathers data from around 150,000 users, with Node.js handling back-end processing and caching for optimized performance. Users can explore and analyze their social networks in an intuitive and visually appealing way.</p>
    </>;

    public static smartMirrorExpanded = <>
        <p className={styles.paragraph}>Smart Mirror is a Raspberry Pi 4 dashboard mounted behind a framed mirror front and built on MagicMirror v2.34.0, launched through Electron on a local-only `localhost:8080` surface so the UI stays private while still driving a full-screen household display.</p>
        <p className={styles.paragraph}>The deployed layout is tuned for Greek day-to-day information: Greek locale and time formatting, an ICS-backed holiday calendar, a bottom-bar RSS newsfeed, a stock watchlist, and layered Open-Meteo widgets for Porto Rafti, Loutsa, and Anavyssos. I also patched the core weather module so the mirror can show 3-hour forecasts for today only, wind direction arrows, and knot-based wind speeds that are easier to read from across the room.</p>
        <p className={styles.paragraph}>The control plane is custom. A Node-based Telegram bot manages stock symbols, playback state for a custom `MMM-TelegramVideo` module, brightness for a custom `MMM-DisplayDimmer` module, PIR alert settings, and display sleep timing by editing JSON state files or the live config and safely restarting MagicMirror when needed.</p>
        <p className={styles.paragraph}>On the hardware side, the mirror runs with a PIR motion sensor on GPIO17 and an IMX708 Raspberry Pi camera mounted above the frame. A Python daemon built with `gpiozero` wakes or sleeps the display after inactivity, relaunches MagicMirror if the UI drops, captures snapshots through `rpicam-jpeg` or `libcamera-still`, and can forward motion alerts to Telegram.</p>
        <p className={styles.paragraph}>The repo also includes a local `MMM-CameraFeed` module that exposes an MJPEG stream and writes fresh frames to disk for fallback alert images, so the system can still send a useful snapshot even when the camera is busy. In practice, the project blends frontend layout work, Linux service orchestration, GPIO hardware, camera tooling, and small-but-important product details into one coherent household device.</p>
    </>;

    public static diyAlarmSystemExpanded = <>
        <p className={styles.paragraph}>Smart Home Demo is a DIY alarm system built around an ESP32 paired with an ESP32-CAM module, bringing up NVS, logging, configuration, Wi-Fi provisioning, the control loop, and the UI services in sequence so every dependency is stable before motion events are evaluated.</p>
        <p className={styles.paragraph}>The FreeRTOS loop owns magnetic reed switches on doors and windows, a PIR motion sensor, a BH1750 light sensor, current-limited LED indicators, a relay-driven siren, and inline resistors that tame the mixed-voltage runs, while the camera captures snapshots whenever those inputs cross the configured lux and hold thresholds.</p>
        <p className={styles.paragraph}>Runtime tunables live in NVS-backed JSON patches, but the highlight is the communications stack: NimBLE exposes the provisioning service over classic GATT characteristics for SSID, passphrase, scan results, and state notifications, and ESP-NETIF rides Wi-Fi with a lightweight HTTP/JSON channel that dashboards poll for sensor telemetry and overrides.</p>
        <p className={styles.paragraph}>On the frontend, a TypeScript Web Bluetooth helper exports a `SmartHomeBleClient` EventTarget with filters, fallback UUIDs, and helpers to read, write, provision, and subscribe, while the playground app rebuilds the bundle, drives overrides, streams motion/light/log data, and mirrors the siren controls.</p>
        <p className={styles.paragraph}>Tooling ties it together with an HTTP flash bridge that proxies to `idf.py`, an ESP-IDF sourcing CLI, markdown walkthroughs for hardware bring-up, and a Bleak-based GATT explorer—the workflow is flash, pair over BLE, verify Wi-Fi telemetry, and close with the Puppeteer end-to-end run.</p>
    </>;

    public static machineLearningRoboticalExpanded = <>
        <p className={styles.paragraph}>A tool for creating machine learning models in Scratch without requiring coding or prior expertise. These models can be integrated with Sprites or Robots to respond to predictions.</p>
        <p className={styles.paragraph}>Users can build models in three steps: data collection, model training, and prediction.</p>
        <p className={styles.paragraph}>The tool also supports models from Google's Teachable Machine platform.</p>
        <p className={styles.paragraph}>Built with TensorFlow.js and Service Workers, all processing is handled on the front end.</p>
        <p className={styles.paragraph}>This project introduced the first machine learning feature in Robotical's product lineup.</p>
    </>;

    public static martyQuestExpanded = <>
        <p className={styles.paragraph}>Marty Quest: Code The Town is a tile-based programming adventure for young learners. Players guide Marty through a town, meet short mission goals, and open a Blockly workspace when the world needs a robot solution.</p>
        <p className={styles.paragraph}>The first playable slice is built with Phaser, TypeScript, Vite, Blockly, and Tiled maps. It includes a tutorial plus a Home Street chapter covering sequencing, loops, conditionals, item actions, sorting, and procedure-style repair routines across missions such as First Steps, Bakery, Bridge, Crossing, Cellar Door, Sort Flowers, and Signal Field.</p>
        <p className={styles.paragraph}>I designed the mission model around deterministic tile-space state: Marty has a tile and facing direction, each mission defines allowed blocks, command limits, map bindings, win/fail rules, hints, rewards, and badge thresholds, and the runtime compiles Blockly into a normalized command queue that the simulator executes step by step.</p>
        <p className={styles.paragraph}>The prototype focuses on classroom clarity. It highlights blocks while Marty runs, shows informative failure states for blocked or unsafe moves, saves local progress and draft workspaces, unlocks missions progressively, awards bronze/silver/gold badges by block count, and includes child-friendly Info, Hint, Watch, Reset, and Show Solution flows.</p>
        <p className={styles.paragraph}>The architecture deliberately keeps the command model separate from rendering so the same Blocks to command queue to runtime path can later target a real Marty adapter. That makes the game useful as a simulation-first learning product without closing the door on physical robot transfer.</p>
    </>;

    public static martyControllerExpanded = <>
        <p className={styles.paragraph}>Marty Controller was one of my first projects at Robotical. It is a platform for controlling Marty the Robot, offering two modes: a real-time joystick and a sequencer.</p>
        <p className={styles.paragraph}>In joystick mode, Marty responds instantly to commands, providing real-time control. In sequencer mode, users can create a sequence of commands that Marty will execute in order.</p>
        <p className={styles.paragraph}>While not a complex project, it holds personal significance as it marked the beginning of my journey at Robotical. A before-and-after comparison image is included to showcase improvements made during the update.</p>
    </>;

    public static learningPortalExpanded = <>
        <p className={styles.paragraph}>The Learning Portal is a platform offering over 100 courses on robotics and Marty. It is built with Next.js for both the front and back end, with content managed through Sanity.io.</p>
        <p className={styles.paragraph}>This project replaced an older Gatsby-based static site, introducing features such as dynamic filtering, server-side rendering, and a caching mechanism for improved performance.</p>
        <p className={styles.paragraph}>The platform aligns with educational standards from multiple regions, including Australia, the UK, the US, and more. Migrating to Next.js enabled dynamic content delivery based on the user's location, with plans to incorporate comments and reviews for lessons and activities in the future.</p>
    </>;

    public static codeAssessExpanded = <>
        <p className={styles.paragraph}>Code Assess is a platform designed to support teachers in delivering computer science and programming education, particularly for non-specialist educators.</p>
        <p className={styles.paragraph}>It assists teachers by automating assessment, identifying students who need additional support, and those ready for advanced challenges. The platform evaluates students' understanding of coding concepts, regardless of the specific code they create.</p>
        <p className={styles.paragraph}>Compatible with existing Scratch-based lessons, with or without Marty, it provides insights into coding habits and student engagement. The platform tracks competency development over time and offers detailed reports via a teacher dashboard.</p>
        <p className={styles.paragraph}>Future updates will introduce personalized lesson recommendations and progress badges for students, as well as performance reports for school administrators to support curriculum planning and communication with stakeholders.</p>
        <p className={styles.paragraph}>The platform leverages WebSockets for real-time communication between clients and the server, ensuring seamless interaction and updates.</p>
    </>;

    public static cogMiniGamesExpanded = <>
        <p className={styles.paragraph}>A collection of mini-games designed for Cog, Robotical's educational device, aimed at introducing young learners to fundamental programming concepts and ScratchJr.</p>
        <p className={styles.paragraph}>Games include:</p>
        <ul>
            <li><strong>Code Wheel:</strong> Introduces sequencing by demonstrating how code blocks execute in order.</li>
            <li><strong>Jumping Game:</strong> Players use Cog as a joystick to avoid obstacles, learning about event-based programming.</li>
            <li><strong>Maze:</strong> A 2D maze where players associate Cog's tilt actions with directional movement, reinforcing event handling concepts.</li>
        </ul>
        <br />
        <p className={styles.paragraph}>Instead of using a keyboard, the games utilize Cog's IR and accelerometer sensors to interact with the gameplay.</p>
    </>;

    public static blocksToPythonExpanded = <>
        <p className={styles.paragraph}>Feedback from users highlighted challenges in moving from block-based programming to Python due to differences in syntax and complexity.</p>
        <p className={styles.paragraph}>So the Blocks to Python transpiler is a feature that converts Scratch blocks into Python code, bridging the gap between visual and text-based programming.</p>
        <p className={styles.paragraph}>This feature allows young learners to control Marty the Robot using either Scratch or Python, helping them transition between the two environments.</p>
    </>;

    public static sensorsDashboardExpanded = <>
        <p className={styles.paragraph}>The Sensors Dashboard is a data visualization tool for Marty the Robot, providing insights from various built-in sensors such as color, infrared, light, noise, accelerometer, magnetometer, and more.</p>
        <p className={styles.paragraph}>It serves as an introduction to data science concepts and graphing for young learners, helping them understand real-time data processing.</p>
        <p className={styles.paragraph}>The dashboard is available as a standalone tool and is also integrated into MartyBlocks, Robotical's Scratch-based programming environment, allowing users to visualize sensor data as they interact with Marty.</p>
    </>;

    public static scratchJrWebExpanded = <>
        <p className={styles.paragraph}>ScratchJr Web is a web-based adaptation of the ScratchJr platform, originally developed for mobile devices. Due to high demand, a web version was created to provide broader accessibility.</p>
        <p className={styles.paragraph}>To the best of my knowledge, there are no other web-based implementations of ScratchJr available online. While a desktop version exists, it relies on Electron.</p>
        <p className={styles.paragraph}>One of the key challenges was implementing a front-end database for asset storage, similar to the phone application version. LocalStorage was not a suitable option, so IndexedDB was used instead.</p>
        <p className={styles.paragraph}>IndexedDB, a low-level NoSQL database built into modern web browsers, allows efficient client-side storage of structured data, making it a fitting solution for managing assets within the application.</p>
    </>;

    public static newsHubExpanded = <>
        <p className={styles.paragraph}>News Hub is a feature developed to facilitate communication with users of Marty the Robot, implemented in under two days to address the need for firmware update notifications.</p>
        <p className={styles.paragraph}>It enables targeted communication with users running outdated firmware, allowing them to receive relevant update alerts. Additionally, the platform supports two-way interaction, enabling users to provide feedback and respond to a weekly question that refreshes periodically.</p>
    </>;

    public static dreamsForLittlesExpanded = <>
        <p className={styles.paragraph}>Dreams for Littles is a baby activity tracking app available for iOS and Android devices, allowing users to log activities such as breastfeeding, diaper changes, and more.</p>
        <p className={styles.paragraph}>The app provides data analysis and visualization features in the analysis tab, which is accessible through a premium subscription.</p>
        <p className={styles.paragraph}>Additional features include reminders and notifications to help parents stay organized.</p>
    </>;

    public static littlesBabyTrackerExpanded = <>
        <p className={styles.paragraph}>LittlesBabyTracker is the multi-tenant evolution of the Dreams for Littles product: a sleep-coaching SaaS where families track baby sleep and care activity while sleep coaches manage the families assigned to their practice.</p>
        <p className={styles.paragraph}>The system is split across a coach admin dashboard, a separate owner portal for global super-admin operations, a mobile-first web application for families and coaches, and a thin React Native phone shell. Product logic and tenant decisions live in the web app and platform API rather than the native wrapper.</p>
        <p className={styles.paragraph}>The platform API verifies Supabase Auth JWTs, maps identities to application users, and enforces organization, coach, family, assignment, and entitlement boundaries. Supabase Postgres stores tenants, memberships, invite codes, family assignments, babies, activity logs, billing state, release records, audit events, and access entitlements through Prisma-backed services.</p>
        <p className={styles.paragraph}>The coach workflow includes Stripe-backed subscriptions, invite-code creation, family assignment and revocation, scoped activity visibility, dashboard analytics, support FAQs, and operational notifications. The owner portal stays separate for platform-wide coaches, families, billing, analytics, release operations, feedback, and notification banners.</p>
        <p className={styles.paragraph}>The phone app combines a React Native store binary with versioned mobile-web releases. The wrapper asks the backend for the newest compatible web release, verifies the zip checksum, caches it locally, serves it through a local static server, and rolls forward or back without putting tenant authorization into native code.</p>
    </>;




    /* Small descriptions */
    public static worldAtlas = getTxtFromJsx(ProjectsText.worldAtlasExpanded);
    public static restaurant = getTxtFromJsx(ProjectsText.restaurantExpanded);
    public static checkers = getTxtFromJsx(ProjectsText.checkersExpanded);
    public static reinforcementLearning = getTxtFromJsx(ProjectsText.reinforcementLearningExpanded);
    public static xcovers = getTxtFromJsx(ProjectsText.xcoversExpanded);
    public static onlineExperiment1 = getTxtFromJsx(ProjectsText.onlineExperiment1Expanded);
    public static blackJack = getTxtFromJsx(ProjectsText.blackJackExpanded);
    public static networkGraph = getTxtFromJsx(ProjectsText.networkGraphExpanded);
    public static smartPot = getTxtFromJsx(ProjectsText.smartPotExpanded);
    public static smartMirror = getTxtFromJsx(ProjectsText.smartMirrorExpanded);
    public static diyAlarmSystem = getTxtFromJsx(ProjectsText.diyAlarmSystemExpanded);
    public static machineLearningRobotical = getTxtFromJsx(ProjectsText.machineLearningRoboticalExpanded);
    public static martyQuest = getTxtFromJsx(ProjectsText.martyQuestExpanded);
    public static martyController = getTxtFromJsx(ProjectsText.martyControllerExpanded);
    public static learningPortal = getTxtFromJsx(ProjectsText.learningPortalExpanded);
    public static codeAssess = getTxtFromJsx(ProjectsText.codeAssessExpanded);
    public static cogMiniGames = getTxtFromJsx(ProjectsText.cogMiniGamesExpanded);
    public static blocksToPython = getTxtFromJsx(ProjectsText.blocksToPythonExpanded);
    public static sensorsDashboard = getTxtFromJsx(ProjectsText.sensorsDashboardExpanded);
    public static scratchJrWeb = getTxtFromJsx(ProjectsText.scratchJrWebExpanded);
    public static newsHub = getTxtFromJsx(ProjectsText.newsHubExpanded);
    public static dreamsForLittles = getTxtFromJsx(ProjectsText.dreamsForLittlesExpanded);
    public static littlesBabyTracker = getTxtFromJsx(ProjectsText.littlesBabyTrackerExpanded);

}

export default ProjectsText;
